spring.application.name=sherlockhomes

# Conexi\u00f3n a MySQL Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/nombre_de_tu_bd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_contrase\u00f1a_de_mysql

# Crear/actualizar tablas de forma autom\u00e1tica
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true